# Generated by Django 6.0.6 on 2026-06-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanCareApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='confirm_password',
        ),
    ]
