# Generated by Django 6.0.6 on 2026-06-11 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanCareApp', '0002_remove_providerprofile_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='czn_back',
            field=models.ImageField(blank=True, null=True, upload_to='credentials/citizenship_back/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='czn_front',
            field=models.ImageField(blank=True, null=True, upload_to='credentials/citizenship_front/'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='service_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
